# Generated by Django 5.2.1 on 2025-06-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('precio_original', models.FloatField()),
                ('descuento', models.FloatField()),
                ('precio_oferta', models.FloatField()),
                ('url_imagen', models.URLField()),
                ('link_referidos', models.URLField()),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
    ]
