# Generated by Django 5.2.1 on 2025-06-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productooferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productooferta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productooferta',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productooferta',
            name='precio_original',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
