# Generated by Django 5.2.1 on 2025-06-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_productooferta_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productooferta',
            name='precio_oferta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
