# Generated by Django 5.2.12 on 2026-04-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_productooferta_precio_oferta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productooferta",
            name="categoria",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="productooferta",
            name="fecha",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="productooferta",
            name="titulo",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
