# Generated by Django 5.2.1 on 2026-04-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_add_indexes_fecha_categoria_titulo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdsReportSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        choices=[
                            ("matmarkt", "MatMarkt"),
                            ("cortina", "Cortina Hawaiana"),
                            ("both", "Both"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("report_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("raw_report", models.TextField()),
                ("analysis", models.TextField(blank=True, default="")),
                ("campaign_metrics", models.JSONField(blank=True, default=list)),
                ("is_auto_saved", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-report_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "report_date"],
                        name="api_adsrepo_account_40cf03_idx",
                    )
                ],
            },
        ),
    ]
