# Generated by Django 5.2.1 on 2026-04-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_seed_reglas_hulempak'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='factura',
            new_name='api_factura_fecha_545207_idx',
            old_name='api_factura_fecha_b9c1e2_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientobanco',
            new_name='api_movimie_fecha_cddaf9_idx',
            old_name='api_movimi_fecha_8a6a4d_idx',
        ),
        migrations.AddField(
            model_name='factura',
            name='comentario_override',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='factura',
            name='override_manual',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
